// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.wavefront.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.wavefront.outputs.DashboardSectionRowChart;
import java.util.List;
import java.util.Objects;

@CustomType
public final class DashboardSectionRow {
    /**
     * @return Charts in this section. See dashboard chart.
     * 
     */
    private List<DashboardSectionRowChart> charts;

    private DashboardSectionRow() {}
    /**
     * @return Charts in this section. See dashboard chart.
     * 
     */
    public List<DashboardSectionRowChart> charts() {
        return this.charts;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DashboardSectionRow defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<DashboardSectionRowChart> charts;
        public Builder() {}
        public Builder(DashboardSectionRow defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.charts = defaults.charts;
        }

        @CustomType.Setter
        public Builder charts(List<DashboardSectionRowChart> charts) {
            this.charts = Objects.requireNonNull(charts);
            return this;
        }
        public Builder charts(DashboardSectionRowChart... charts) {
            return charts(List.of(charts));
        }
        public DashboardSectionRow build() {
            final var _resultValue = new DashboardSectionRow();
            _resultValue.charts = charts;
            return _resultValue;
        }
    }
}
