// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.wavefront.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetAlertsAlertFailingHostLabelPair {
    private Integer firing;
    private String host;

    private GetAlertsAlertFailingHostLabelPair() {}
    public Integer firing() {
        return this.firing;
    }
    public String host() {
        return this.host;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAlertsAlertFailingHostLabelPair defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer firing;
        private String host;
        public Builder() {}
        public Builder(GetAlertsAlertFailingHostLabelPair defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.firing = defaults.firing;
    	      this.host = defaults.host;
        }

        @CustomType.Setter
        public Builder firing(Integer firing) {
            this.firing = Objects.requireNonNull(firing);
            return this;
        }
        @CustomType.Setter
        public Builder host(String host) {
            this.host = Objects.requireNonNull(host);
            return this;
        }
        public GetAlertsAlertFailingHostLabelPair build() {
            final var _resultValue = new GetAlertsAlertFailingHostLabelPair();
            _resultValue.firing = firing;
            _resultValue.host = host;
            return _resultValue;
        }
    }
}
