// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.wavefront.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetAlertsAlertInMaintenanceHostLabelPair {
    private Integer firing;
    private String host;

    private GetAlertsAlertInMaintenanceHostLabelPair() {}
    public Integer firing() {
        return this.firing;
    }
    public String host() {
        return this.host;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAlertsAlertInMaintenanceHostLabelPair defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer firing;
        private String host;
        public Builder() {}
        public Builder(GetAlertsAlertInMaintenanceHostLabelPair defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.firing = defaults.firing;
    	      this.host = defaults.host;
        }

        @CustomType.Setter
        public Builder firing(Integer firing) {
            if (firing == null) {
              throw new MissingRequiredPropertyException("GetAlertsAlertInMaintenanceHostLabelPair", "firing");
            }
            this.firing = firing;
            return this;
        }
        @CustomType.Setter
        public Builder host(String host) {
            if (host == null) {
              throw new MissingRequiredPropertyException("GetAlertsAlertInMaintenanceHostLabelPair", "host");
            }
            this.host = host;
            return this;
        }
        public GetAlertsAlertInMaintenanceHostLabelPair build() {
            final var _resultValue = new GetAlertsAlertInMaintenanceHostLabelPair();
            _resultValue.firing = firing;
            _resultValue.host = host;
            return _resultValue;
        }
    }
}
