// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.wavefront.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetUserGroupsUserGroup {
    /**
     * @return The group description.
     * 
     */
    private String description;
    /**
     * @return The group ID.
     * 
     */
    private String id;
    /**
     * @return The group name.
     * 
     */
    private String name;
    /**
     * @return List of roles associated with the group.
     * 
     */
    private List<String> roles;
    /**
     * @return List of users assigned to the group.
     * 
     */
    private List<String> users;

    private GetUserGroupsUserGroup() {}
    /**
     * @return The group description.
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return The group ID.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The group name.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return List of roles associated with the group.
     * 
     */
    public List<String> roles() {
        return this.roles;
    }
    /**
     * @return List of users assigned to the group.
     * 
     */
    public List<String> users() {
        return this.users;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetUserGroupsUserGroup defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String description;
        private String id;
        private String name;
        private List<String> roles;
        private List<String> users;
        public Builder() {}
        public Builder(GetUserGroupsUserGroup defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.description = defaults.description;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.roles = defaults.roles;
    	      this.users = defaults.users;
        }

        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetUserGroupsUserGroup", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetUserGroupsUserGroup", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetUserGroupsUserGroup", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder roles(List<String> roles) {
            if (roles == null) {
              throw new MissingRequiredPropertyException("GetUserGroupsUserGroup", "roles");
            }
            this.roles = roles;
            return this;
        }
        public Builder roles(String... roles) {
            return roles(List.of(roles));
        }
        @CustomType.Setter
        public Builder users(List<String> users) {
            if (users == null) {
              throw new MissingRequiredPropertyException("GetUserGroupsUserGroup", "users");
            }
            this.users = users;
            return this;
        }
        public Builder users(String... users) {
            return users(List.of(users));
        }
        public GetUserGroupsUserGroup build() {
            final var _resultValue = new GetUserGroupsUserGroup();
            _resultValue.description = description;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.roles = roles;
            _resultValue.users = users;
            return _resultValue;
        }
    }
}
