provider: wavefront
major-version: 3
esc:
    enabled: true
env:
    WAVEFRONT_ADDRESS: ${{ secrets.WAVEFRONT_ADDRESS }}
    WAVEFRONT_TOKEN: ${{ secrets.WAVEFRONT_TOKEN }}
makeTemplate: bridged
team: ecosystem
pulumiConvert: 1
registryDocs: true
