provider: wavefront
major-version: 3
env:
  WAVEFRONT_ADDRESS: ${{ secrets.WAVEFRONT_ADDRESS }}
  WAVEFRONT_TOKEN: ${{ secrets.WAVEFRONT_TOKEN }}
makeTemplate: bridged
team: ecosystem
pulumiConvert: 1
plugins:
  - name: terraform
    version: "1.0.16"
    kind: converter
