// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Wavefront
{
    public partial class CloudIntegrationAppDynamics : Pulumi.CustomResource
    {
        [Output("additionalTags")]
        public Output<ImmutableDictionary<string, string>?> AdditionalTags { get; private set; } = null!;

        [Output("appFilterRegexes")]
        public Output<ImmutableArray<string>> AppFilterRegexes { get; private set; } = null!;

        [Output("controllerName")]
        public Output<string> ControllerName { get; private set; } = null!;

        [Output("enableAppInfraMetrics")]
        public Output<bool?> EnableAppInfraMetrics { get; private set; } = null!;

        [Output("enableBackendMetrics")]
        public Output<bool?> EnableBackendMetrics { get; private set; } = null!;

        [Output("enableBusinessTrxMetrics")]
        public Output<bool?> EnableBusinessTrxMetrics { get; private set; } = null!;

        [Output("enableErrorMetrics")]
        public Output<bool?> EnableErrorMetrics { get; private set; } = null!;

        [Output("enableIndividualNodeMetrics")]
        public Output<bool?> EnableIndividualNodeMetrics { get; private set; } = null!;

        [Output("enableOverallPerfMetrics")]
        public Output<bool?> EnableOverallPerfMetrics { get; private set; } = null!;

        [Output("enableRollup")]
        public Output<bool?> EnableRollup { get; private set; } = null!;

        [Output("enableServiceEndpointMetrics")]
        public Output<bool?> EnableServiceEndpointMetrics { get; private set; } = null!;

        [Output("encryptedPassword")]
        public Output<string> EncryptedPassword { get; private set; } = null!;

        [Output("forceSave")]
        public Output<bool?> ForceSave { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("service")]
        public Output<string> Service { get; private set; } = null!;

        [Output("serviceRefreshRateInMinutes")]
        public Output<int?> ServiceRefreshRateInMinutes { get; private set; } = null!;

        [Output("userName")]
        public Output<string> UserName { get; private set; } = null!;


        /// <summary>
        /// Create a CloudIntegrationAppDynamics resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public CloudIntegrationAppDynamics(string name, CloudIntegrationAppDynamicsArgs args, CustomResourceOptions? options = null)
            : base("wavefront:index/cloudIntegrationAppDynamics:CloudIntegrationAppDynamics", name, args ?? new CloudIntegrationAppDynamicsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private CloudIntegrationAppDynamics(string name, Input<string> id, CloudIntegrationAppDynamicsState? state = null, CustomResourceOptions? options = null)
            : base("wavefront:index/cloudIntegrationAppDynamics:CloudIntegrationAppDynamics", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing CloudIntegrationAppDynamics resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static CloudIntegrationAppDynamics Get(string name, Input<string> id, CloudIntegrationAppDynamicsState? state = null, CustomResourceOptions? options = null)
        {
            return new CloudIntegrationAppDynamics(name, id, state, options);
        }
    }

    public sealed class CloudIntegrationAppDynamicsArgs : Pulumi.ResourceArgs
    {
        [Input("additionalTags")]
        private InputMap<string>? _additionalTags;
        public InputMap<string> AdditionalTags
        {
            get => _additionalTags ?? (_additionalTags = new InputMap<string>());
            set => _additionalTags = value;
        }

        [Input("appFilterRegexes")]
        private InputList<string>? _appFilterRegexes;
        public InputList<string> AppFilterRegexes
        {
            get => _appFilterRegexes ?? (_appFilterRegexes = new InputList<string>());
            set => _appFilterRegexes = value;
        }

        [Input("controllerName", required: true)]
        public Input<string> ControllerName { get; set; } = null!;

        [Input("enableAppInfraMetrics")]
        public Input<bool>? EnableAppInfraMetrics { get; set; }

        [Input("enableBackendMetrics")]
        public Input<bool>? EnableBackendMetrics { get; set; }

        [Input("enableBusinessTrxMetrics")]
        public Input<bool>? EnableBusinessTrxMetrics { get; set; }

        [Input("enableErrorMetrics")]
        public Input<bool>? EnableErrorMetrics { get; set; }

        [Input("enableIndividualNodeMetrics")]
        public Input<bool>? EnableIndividualNodeMetrics { get; set; }

        [Input("enableOverallPerfMetrics")]
        public Input<bool>? EnableOverallPerfMetrics { get; set; }

        [Input("enableRollup")]
        public Input<bool>? EnableRollup { get; set; }

        [Input("enableServiceEndpointMetrics")]
        public Input<bool>? EnableServiceEndpointMetrics { get; set; }

        [Input("encryptedPassword", required: true)]
        public Input<string> EncryptedPassword { get; set; } = null!;

        [Input("forceSave")]
        public Input<bool>? ForceSave { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("service", required: true)]
        public Input<string> Service { get; set; } = null!;

        [Input("serviceRefreshRateInMinutes")]
        public Input<int>? ServiceRefreshRateInMinutes { get; set; }

        [Input("userName", required: true)]
        public Input<string> UserName { get; set; } = null!;

        public CloudIntegrationAppDynamicsArgs()
        {
        }
    }

    public sealed class CloudIntegrationAppDynamicsState : Pulumi.ResourceArgs
    {
        [Input("additionalTags")]
        private InputMap<string>? _additionalTags;
        public InputMap<string> AdditionalTags
        {
            get => _additionalTags ?? (_additionalTags = new InputMap<string>());
            set => _additionalTags = value;
        }

        [Input("appFilterRegexes")]
        private InputList<string>? _appFilterRegexes;
        public InputList<string> AppFilterRegexes
        {
            get => _appFilterRegexes ?? (_appFilterRegexes = new InputList<string>());
            set => _appFilterRegexes = value;
        }

        [Input("controllerName")]
        public Input<string>? ControllerName { get; set; }

        [Input("enableAppInfraMetrics")]
        public Input<bool>? EnableAppInfraMetrics { get; set; }

        [Input("enableBackendMetrics")]
        public Input<bool>? EnableBackendMetrics { get; set; }

        [Input("enableBusinessTrxMetrics")]
        public Input<bool>? EnableBusinessTrxMetrics { get; set; }

        [Input("enableErrorMetrics")]
        public Input<bool>? EnableErrorMetrics { get; set; }

        [Input("enableIndividualNodeMetrics")]
        public Input<bool>? EnableIndividualNodeMetrics { get; set; }

        [Input("enableOverallPerfMetrics")]
        public Input<bool>? EnableOverallPerfMetrics { get; set; }

        [Input("enableRollup")]
        public Input<bool>? EnableRollup { get; set; }

        [Input("enableServiceEndpointMetrics")]
        public Input<bool>? EnableServiceEndpointMetrics { get; set; }

        [Input("encryptedPassword")]
        public Input<string>? EncryptedPassword { get; set; }

        [Input("forceSave")]
        public Input<bool>? ForceSave { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("service")]
        public Input<string>? Service { get; set; }

        [Input("serviceRefreshRateInMinutes")]
        public Input<int>? ServiceRefreshRateInMinutes { get; set; }

        [Input("userName")]
        public Input<string>? UserName { get; set; }

        public CloudIntegrationAppDynamicsState()
        {
        }
    }
}
