// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Wavefront
{
    public static class GetDefaultUserGroup
    {
        /// <summary>
        /// Use this data source to get the Group ID of the `Everyone` group in Wavefront.
        /// </summary>
        public static Task<GetDefaultUserGroupResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDefaultUserGroupResult>("wavefront:index/getDefaultUserGroup:getDefaultUserGroup", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Use this data source to get the Group ID of the `Everyone` group in Wavefront.
        /// </summary>
        public static Output<GetDefaultUserGroupResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDefaultUserGroupResult>("wavefront:index/getDefaultUserGroup:getDefaultUserGroup", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetDefaultUserGroupResult
    {
        /// <summary>
        /// Set to the Group ID of the `Everyone` group, suitable for referencing
        /// in other resources that support group memberships.
        /// </summary>
        public readonly string GroupId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetDefaultUserGroupResult(
            string groupId,

            string id)
        {
            GroupId = groupId;
            Id = id;
        }
    }
}
