// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Wavefront
{
    public static class GetExternalLinks
    {
        /// <summary>
        /// Use this data source to get information about all Wavefront external links.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using Wavefront = Pulumi.Wavefront;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Wavefront.GetExternalLinks.Invoke(new()
        ///     {
        ///         Limit = 10,
        ///         Offset = 0,
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetExternalLinksResult> InvokeAsync(GetExternalLinksArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetExternalLinksResult>("wavefront:index/getExternalLinks:getExternalLinks", args ?? new GetExternalLinksArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to get information about all Wavefront external links.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using Wavefront = Pulumi.Wavefront;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Wavefront.GetExternalLinks.Invoke(new()
        ///     {
        ///         Limit = 10,
        ///         Offset = 0,
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetExternalLinksResult> Invoke(GetExternalLinksInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetExternalLinksResult>("wavefront:index/getExternalLinks:getExternalLinks", args ?? new GetExternalLinksInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetExternalLinksArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Limit is the maximum number of results to be returned. Defaults to 100.
        /// </summary>
        [Input("limit")]
        public int? Limit { get; set; }

        /// <summary>
        /// Offset is the offset from the first result to be returned. Defaults to 0.
        /// </summary>
        [Input("offset")]
        public int? Offset { get; set; }

        public GetExternalLinksArgs()
        {
        }
        public static new GetExternalLinksArgs Empty => new GetExternalLinksArgs();
    }

    public sealed class GetExternalLinksInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Limit is the maximum number of results to be returned. Defaults to 100.
        /// </summary>
        [Input("limit")]
        public Input<int>? Limit { get; set; }

        /// <summary>
        /// Offset is the offset from the first result to be returned. Defaults to 0.
        /// </summary>
        [Input("offset")]
        public Input<int>? Offset { get; set; }

        public GetExternalLinksInvokeArgs()
        {
        }
        public static new GetExternalLinksInvokeArgs Empty => new GetExternalLinksInvokeArgs();
    }


    [OutputType]
    public sealed class GetExternalLinksResult
    {
        /// <summary>
        /// List of all external links in Wavefront. For each external link you will see a list of attributes.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetExternalLinksExternalLinkResult> ExternalLinks;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly int? Limit;
        public readonly int? Offset;

        [OutputConstructor]
        private GetExternalLinksResult(
            ImmutableArray<Outputs.GetExternalLinksExternalLinkResult> externalLinks,

            string id,

            int? limit,

            int? offset)
        {
            ExternalLinks = externalLinks;
            Id = id;
            Limit = limit;
            Offset = offset;
        }
    }
}
