// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.wavefront;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.wavefront.CloudIntegrationGcpArgs;
import com.pulumi.wavefront.Utilities;
import com.pulumi.wavefront.inputs.CloudIntegrationGcpState;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Provides a Wavefront Cloud Integration for Google Cloud Platform. This allows Google Cloud Platform cloud
 * integrations to be created, updated, and deleted.
 * 
 * ## Example Usage
 * 
 * ## Import
 * 
 * GCP Cloud Integrations can be imported by using the `id`, e.g.
 * 
 * ```sh
 *  $ pulumi import wavefront:index/cloudIntegrationGcp:CloudIntegrationGcp gcp a411c16b-3cf7-4f03-bf11-8ca05aab898d
 * ```
 * 
 */
@ResourceType(type="wavefront:index/cloudIntegrationGcp:CloudIntegrationGcp")
public class CloudIntegrationGcp extends com.pulumi.resources.CustomResource {
    /**
     * A list of point tag key-values to add to every point ingested using this integration.
     * 
     */
    @Export(name="additionalTags", type=Map.class, parameters={String.class, String.class})
    private Output</* @Nullable */ Map<String,String>> additionalTags;

    /**
     * @return A list of point tag key-values to add to every point ingested using this integration.
     * 
     */
    public Output<Optional<Map<String,String>>> additionalTags() {
        return Codegen.optional(this.additionalTags);
    }
    /**
     * A list of Google Cloud Platform (GCP) services.  Valid values are `APPENGINE`,
     * `BIGQUERY`, `BIGTABLE`, `CLOUDFUNCTIONS`, `CLOUDIOT`, `CLOUDSQL`, `CLOUDTASKS`, `COMPUTE`, `CONTAINER`,
     * `DATAFLOW`, `DATAPROC`, `DATASTORE`, `FIREBASEDATABASE`, `FIREBASEHOSTING`, `FIRESTORE`, `INTERCONNECT`,
     * `LOADBALANCING`, `LOGGING`, `ML`, `MONITORING`, `PUBSUB`, `REDIS`, `ROUTER`, `SERVICERUNTIME`, `SPANNER`, `STORAGE`,
     * `TPU`, and `VPN`.
     * 
     */
    @Export(name="categories", type=List.class, parameters={String.class})
    private Output</* @Nullable */ List<String>> categories;

    /**
     * @return A list of Google Cloud Platform (GCP) services.  Valid values are `APPENGINE`,
     * `BIGQUERY`, `BIGTABLE`, `CLOUDFUNCTIONS`, `CLOUDIOT`, `CLOUDSQL`, `CLOUDTASKS`, `COMPUTE`, `CONTAINER`,
     * `DATAFLOW`, `DATAPROC`, `DATASTORE`, `FIREBASEDATABASE`, `FIREBASEHOSTING`, `FIRESTORE`, `INTERCONNECT`,
     * `LOADBALANCING`, `LOGGING`, `ML`, `MONITORING`, `PUBSUB`, `REDIS`, `ROUTER`, `SERVICERUNTIME`, `SPANNER`, `STORAGE`,
     * `TPU`, and `VPN`.
     * 
     */
    public Output<Optional<List<String>>> categories() {
        return Codegen.optional(this.categories);
    }
    /**
     * Forces this resource to save, even if errors are present.
     * 
     */
    @Export(name="forceSave", type=Boolean.class, parameters={})
    private Output</* @Nullable */ Boolean> forceSave;

    /**
     * @return Forces this resource to save, even if errors are present.
     * 
     */
    public Output<Optional<Boolean>> forceSave() {
        return Codegen.optional(this.forceSave);
    }
    /**
     * Private key for a Google Cloud Platform (GCP) service account within your project.
     * The account must have at least Viewer permissions. This key must be in the JSON format generated by GCP.
     * 
     */
    @Export(name="jsonKey", type=String.class, parameters={})
    private Output<String> jsonKey;

    /**
     * @return Private key for a Google Cloud Platform (GCP) service account within your project.
     * The account must have at least Viewer permissions. This key must be in the JSON format generated by GCP.
     * 
     */
    public Output<String> jsonKey() {
        return this.jsonKey;
    }
    /**
     * A regular expression that a metric name must match (case-insensitively) in order to be ingested.
     * 
     */
    @Export(name="metricFilterRegex", type=String.class, parameters={})
    private Output</* @Nullable */ String> metricFilterRegex;

    /**
     * @return A regular expression that a metric name must match (case-insensitively) in order to be ingested.
     * 
     */
    public Output<Optional<String>> metricFilterRegex() {
        return Codegen.optional(this.metricFilterRegex);
    }
    /**
     * The human-readable name of this integration.
     * 
     */
    @Export(name="name", type=String.class, parameters={})
    private Output<String> name;

    /**
     * @return The human-readable name of this integration.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The Google Cloud Platform (GCP) Project ID.
     * 
     */
    @Export(name="projectId", type=String.class, parameters={})
    private Output<String> projectId;

    /**
     * @return The Google Cloud Platform (GCP) Project ID.
     * 
     */
    public Output<String> projectId() {
        return this.projectId;
    }
    /**
     * A value denoting which cloud service this service integrates with.
     * 
     */
    @Export(name="service", type=String.class, parameters={})
    private Output<String> service;

    /**
     * @return A value denoting which cloud service this service integrates with.
     * 
     */
    public Output<String> service() {
        return this.service;
    }
    /**
     * How often, in minutes, to refresh the service.
     * 
     */
    @Export(name="serviceRefreshRateInMinutes", type=Integer.class, parameters={})
    private Output</* @Nullable */ Integer> serviceRefreshRateInMinutes;

    /**
     * @return How often, in minutes, to refresh the service.
     * 
     */
    public Output<Optional<Integer>> serviceRefreshRateInMinutes() {
        return Codegen.optional(this.serviceRefreshRateInMinutes);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public CloudIntegrationGcp(String name) {
        this(name, CloudIntegrationGcpArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public CloudIntegrationGcp(String name, CloudIntegrationGcpArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public CloudIntegrationGcp(String name, CloudIntegrationGcpArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("wavefront:index/cloudIntegrationGcp:CloudIntegrationGcp", name, args == null ? CloudIntegrationGcpArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private CloudIntegrationGcp(String name, Output<String> id, @Nullable CloudIntegrationGcpState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("wavefront:index/cloudIntegrationGcp:CloudIntegrationGcp", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static CloudIntegrationGcp get(String name, Output<String> id, @Nullable CloudIntegrationGcpState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new CloudIntegrationGcp(name, id, state, options);
    }
}
