// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.wavefront;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.wavefront.CloudIntegrationAppDynamicsArgs;
import com.pulumi.wavefront.Utilities;
import com.pulumi.wavefront.inputs.CloudIntegrationAppDynamicsState;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Provides a Wavefront Cloud Integration for AppDynamics. This allows AppDynamics cloud integrations to be created,
 * updated, and deleted.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.wavefront.CloudIntegrationAppDynamics;
 * import com.pulumi.wavefront.CloudIntegrationAppDynamicsArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var appDynamics = new CloudIntegrationAppDynamics("appDynamics", CloudIntegrationAppDynamicsArgs.builder()
 *             .name("Test Integration")
 *             .userName("example")
 *             .controllerName("exampleController")
 *             .encryptedPassword("encryptedPassword")
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * AppDynamic Cloud Integrations can be imported by using the `id`, e.g.:
 * 
 * ```sh
 * $ pulumi import wavefront:index/cloudIntegrationAppDynamics:CloudIntegrationAppDynamics app_dynamics a411c16b-3cf7-4f03-bf11-8ca05aab898d
 * ```
 * 
 */
@ResourceType(type="wavefront:index/cloudIntegrationAppDynamics:CloudIntegrationAppDynamics")
public class CloudIntegrationAppDynamics extends com.pulumi.resources.CustomResource {
    /**
     * A list of point tag key-values to add to every point ingested using this integration.
     * 
     */
    @Export(name="additionalTags", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> additionalTags;

    /**
     * @return A list of point tag key-values to add to every point ingested using this integration.
     * 
     */
    public Output<Optional<Map<String,String>>> additionalTags() {
        return Codegen.optional(this.additionalTags);
    }
    /**
     * List of regular expressions that an application name must match (case-insensitively)
     * in order to be ingested.
     * 
     */
    @Export(name="appFilterRegexes", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> appFilterRegexes;

    /**
     * @return List of regular expressions that an application name must match (case-insensitively)
     * in order to be ingested.
     * 
     */
    public Output<Optional<List<String>>> appFilterRegexes() {
        return Codegen.optional(this.appFilterRegexes);
    }
    /**
     * Name of the SaaS controller.
     * 
     */
    @Export(name="controllerName", refs={String.class}, tree="[0]")
    private Output<String> controllerName;

    /**
     * @return Name of the SaaS controller.
     * 
     */
    public Output<String> controllerName() {
        return this.controllerName;
    }
    /**
     * Boolean flag to control Application Infrastructure metric ingestion.
     * 
     */
    @Export(name="enableAppInfraMetrics", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> enableAppInfraMetrics;

    /**
     * @return Boolean flag to control Application Infrastructure metric ingestion.
     * 
     */
    public Output<Optional<Boolean>> enableAppInfraMetrics() {
        return Codegen.optional(this.enableAppInfraMetrics);
    }
    /**
     * Boolean flag to control Backend metric ingestion.
     * 
     */
    @Export(name="enableBackendMetrics", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> enableBackendMetrics;

    /**
     * @return Boolean flag to control Backend metric ingestion.
     * 
     */
    public Output<Optional<Boolean>> enableBackendMetrics() {
        return Codegen.optional(this.enableBackendMetrics);
    }
    /**
     * Boolean flag to control Business Transaction metric ingestion.
     * 
     */
    @Export(name="enableBusinessTrxMetrics", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> enableBusinessTrxMetrics;

    /**
     * @return Boolean flag to control Business Transaction metric ingestion.
     * 
     */
    public Output<Optional<Boolean>> enableBusinessTrxMetrics() {
        return Codegen.optional(this.enableBusinessTrxMetrics);
    }
    /**
     * Boolean flag to control Error metric ingestion.
     * 
     */
    @Export(name="enableErrorMetrics", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> enableErrorMetrics;

    /**
     * @return Boolean flag to control Error metric ingestion.
     * 
     */
    public Output<Optional<Boolean>> enableErrorMetrics() {
        return Codegen.optional(this.enableErrorMetrics);
    }
    /**
     * Boolean flag to control Individual Node metric ingestion.
     * 
     */
    @Export(name="enableIndividualNodeMetrics", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> enableIndividualNodeMetrics;

    /**
     * @return Boolean flag to control Individual Node metric ingestion.
     * 
     */
    public Output<Optional<Boolean>> enableIndividualNodeMetrics() {
        return Codegen.optional(this.enableIndividualNodeMetrics);
    }
    /**
     * Boolean flag to control Overall Performance metric ingestion.
     * 
     */
    @Export(name="enableOverallPerfMetrics", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> enableOverallPerfMetrics;

    /**
     * @return Boolean flag to control Overall Performance metric ingestion.
     * 
     */
    public Output<Optional<Boolean>> enableOverallPerfMetrics() {
        return Codegen.optional(this.enableOverallPerfMetrics);
    }
    /**
     * Set this to `false` to get separate results for all values within the time range,
     * by default it is `true`.
     * 
     */
    @Export(name="enableRollup", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> enableRollup;

    /**
     * @return Set this to `false` to get separate results for all values within the time range,
     * by default it is `true`.
     * 
     */
    public Output<Optional<Boolean>> enableRollup() {
        return Codegen.optional(this.enableRollup);
    }
    /**
     * Boolean flag to control Service End point metric ingestion.
     * 
     */
    @Export(name="enableServiceEndpointMetrics", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> enableServiceEndpointMetrics;

    /**
     * @return Boolean flag to control Service End point metric ingestion.
     * 
     */
    public Output<Optional<Boolean>> enableServiceEndpointMetrics() {
        return Codegen.optional(this.enableServiceEndpointMetrics);
    }
    /**
     * Password for AppDynamics user.
     * 
     */
    @Export(name="encryptedPassword", refs={String.class}, tree="[0]")
    private Output<String> encryptedPassword;

    /**
     * @return Password for AppDynamics user.
     * 
     */
    public Output<String> encryptedPassword() {
        return this.encryptedPassword;
    }
    /**
     * Forces this resource to save, even if errors are present.
     * 
     */
    @Export(name="forceSave", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> forceSave;

    /**
     * @return Forces this resource to save, even if errors are present.
     * 
     */
    public Output<Optional<Boolean>> forceSave() {
        return Codegen.optional(this.forceSave);
    }
    /**
     * The human-readable name of this integration.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The human-readable name of this integration.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * A value denoting which cloud service this service integrates with.
     * 
     */
    @Export(name="service", refs={String.class}, tree="[0]")
    private Output<String> service;

    /**
     * @return A value denoting which cloud service this service integrates with.
     * 
     */
    public Output<String> service() {
        return this.service;
    }
    /**
     * How often, in minutes, to refresh the service.
     * 
     */
    @Export(name="serviceRefreshRateInMinutes", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> serviceRefreshRateInMinutes;

    /**
     * @return How often, in minutes, to refresh the service.
     * 
     */
    public Output<Optional<Integer>> serviceRefreshRateInMinutes() {
        return Codegen.optional(this.serviceRefreshRateInMinutes);
    }
    /**
     * Username is a combination of userName and the account name.
     * 
     */
    @Export(name="userName", refs={String.class}, tree="[0]")
    private Output<String> userName;

    /**
     * @return Username is a combination of userName and the account name.
     * 
     */
    public Output<String> userName() {
        return this.userName;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public CloudIntegrationAppDynamics(String name) {
        this(name, CloudIntegrationAppDynamicsArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public CloudIntegrationAppDynamics(String name, CloudIntegrationAppDynamicsArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public CloudIntegrationAppDynamics(String name, CloudIntegrationAppDynamicsArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("wavefront:index/cloudIntegrationAppDynamics:CloudIntegrationAppDynamics", name, args == null ? CloudIntegrationAppDynamicsArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private CloudIntegrationAppDynamics(String name, Output<String> id, @Nullable CloudIntegrationAppDynamicsState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("wavefront:index/cloudIntegrationAppDynamics:CloudIntegrationAppDynamics", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "encryptedPassword"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static CloudIntegrationAppDynamics get(String name, Output<String> id, @Nullable CloudIntegrationAppDynamicsState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new CloudIntegrationAppDynamics(name, id, state, options);
    }
}
