// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.wavefront;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.wavefront.CloudIntegrationAwsExternalIdArgs;
import com.pulumi.wavefront.Utilities;
import com.pulumi.wavefront.inputs.CloudIntegrationAwsExternalIdState;
import javax.annotation.Nullable;

/**
 * Provides an External ID for use in Amazon Web Services IAM Roles. This allows External IDs to be created and deleted.
 * 
 * ## Example Usage
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.wavefront.CloudIntegrationAwsExternalId;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var externalId = new CloudIntegrationAwsExternalId("externalId");
 * 
 *     }
 * }
 * }
 * </pre>
 * 
 * ## Import
 * 
 * External IDs can be imported by using the `id`, e.g.:
 * 
 * ```sh
 * $ pulumi import wavefront:index/cloudIntegrationAwsExternalId:CloudIntegrationAwsExternalId external_id uGJdkH3k
 * ```
 * 
 */
@ResourceType(type="wavefront:index/cloudIntegrationAwsExternalId:CloudIntegrationAwsExternalId")
public class CloudIntegrationAwsExternalId extends com.pulumi.resources.CustomResource {
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public CloudIntegrationAwsExternalId(java.lang.String name) {
        this(name, CloudIntegrationAwsExternalIdArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public CloudIntegrationAwsExternalId(java.lang.String name, @Nullable CloudIntegrationAwsExternalIdArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public CloudIntegrationAwsExternalId(java.lang.String name, @Nullable CloudIntegrationAwsExternalIdArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("wavefront:index/cloudIntegrationAwsExternalId:CloudIntegrationAwsExternalId", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private CloudIntegrationAwsExternalId(java.lang.String name, Output<java.lang.String> id, @Nullable CloudIntegrationAwsExternalIdState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("wavefront:index/cloudIntegrationAwsExternalId:CloudIntegrationAwsExternalId", name, state, makeResourceOptions(options, id), false);
    }

    private static CloudIntegrationAwsExternalIdArgs makeArgs(@Nullable CloudIntegrationAwsExternalIdArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? CloudIntegrationAwsExternalIdArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static CloudIntegrationAwsExternalId get(java.lang.String name, Output<java.lang.String> id, @Nullable CloudIntegrationAwsExternalIdState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new CloudIntegrationAwsExternalId(name, id, state, options);
    }
}
