// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.wavefront;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.wavefront.DerivedMetricArgs;
import com.pulumi.wavefront.Utilities;
import com.pulumi.wavefront.inputs.DerivedMetricState;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Provides a Wavefront Derived Metric Resource. This allows derived metrics to be created,
 * updated, and deleted.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.wavefront.DerivedMetric;
 * import com.pulumi.wavefront.DerivedMetricArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var derived = new DerivedMetric(&#34;derived&#34;, DerivedMetricArgs.builder()        
 *             .name(&#34;dummy derived metric&#34;)
 *             .minutes(5)
 *             .query(&#34;aliasMetric(5, \&#34;some.metric\&#34;)&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * Derived Metrics can be imported by using the `id`, e.g.:
 * 
 * ```sh
 * $ pulumi import wavefront:index/derivedMetric:DerivedMetric derived_metric 1577102900578
 * ```
 * 
 */
@ResourceType(type="wavefront:index/derivedMetric:DerivedMetric")
public class DerivedMetric extends com.pulumi.resources.CustomResource {
    /**
     * User-supplied additional explanatory information for the derived metric.
     * 
     */
    @Export(name="additionalInformation", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> additionalInformation;

    /**
     * @return User-supplied additional explanatory information for the derived metric.
     * 
     */
    public Output<Optional<String>> additionalInformation() {
        return Codegen.optional(this.additionalInformation);
    }
    /**
     * How frequently the query generating the derived metric is run.
     * 
     */
    @Export(name="minutes", refs={Integer.class}, tree="[0]")
    private Output<Integer> minutes;

    /**
     * @return How frequently the query generating the derived metric is run.
     * 
     */
    public Output<Integer> minutes() {
        return this.minutes;
    }
    /**
     * The name of the Derived Metric in Wavefront.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the Derived Metric in Wavefront.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * A Wavefront query that is evaluated at regular intervals (default is 1 minute).
     * 
     */
    @Export(name="query", refs={String.class}, tree="[0]")
    private Output<String> query;

    /**
     * @return A Wavefront query that is evaluated at regular intervals (default is 1 minute).
     * 
     */
    public Output<String> query() {
        return this.query;
    }
    /**
     * A set of tags to assign to this resource.
     * 
     */
    @Export(name="tags", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> tags;

    /**
     * @return A set of tags to assign to this resource.
     * 
     */
    public Output<Optional<List<String>>> tags() {
        return Codegen.optional(this.tags);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public DerivedMetric(String name) {
        this(name, DerivedMetricArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public DerivedMetric(String name, DerivedMetricArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public DerivedMetric(String name, DerivedMetricArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("wavefront:index/derivedMetric:DerivedMetric", name, args == null ? DerivedMetricArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private DerivedMetric(String name, Output<String> id, @Nullable DerivedMetricState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("wavefront:index/derivedMetric:DerivedMetric", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static DerivedMetric get(String name, Output<String> id, @Nullable DerivedMetricState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new DerivedMetric(name, id, state, options);
    }
}
