// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Wavefront.Outputs
{

    [OutputType]
    public sealed class DashboardSectionRowChart
    {
        public readonly Outputs.DashboardSectionRowChartChartSetting ChartSetting;
        public readonly string? Description;
        public readonly string Name;
        public readonly ImmutableArray<Outputs.DashboardSectionRowChartSource> Sources;
        public readonly string Summarization;
        public readonly string Units;

        [OutputConstructor]
        private DashboardSectionRowChart(
            Outputs.DashboardSectionRowChartChartSetting chartSetting,

            string? description,

            string name,

            ImmutableArray<Outputs.DashboardSectionRowChartSource> sources,

            string summarization,

            string units)
        {
            ChartSetting = chartSetting;
            Description = description;
            Name = name;
            Sources = sources;
            Summarization = summarization;
            Units = units;
        }
    }
}
