// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Wavefront.Outputs
{

    [OutputType]
    public sealed class DashboardSectionRowChart
    {
        public readonly string? ChartAttribute;
        /// <summary>
        /// Chart settings. See chart settings
        /// </summary>
        public readonly Outputs.DashboardSectionRowChartChartSetting ChartSetting;
        /// <summary>
        /// Description of the chart
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// Name of the source
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Query expression to plot on the chart. See chart source queries
        /// </summary>
        public readonly ImmutableArray<Outputs.DashboardSectionRowChartSource> Sources;
        /// <summary>
        /// Summarization strategy for the chart. MEAN is default. Valid options are, `MEAN`, 
        /// `MEDIAN`, `MIN`, `MAX`, `SUM`, `COUNT`, `LAST`, `FIRST`
        /// </summary>
        public readonly string Summarization;
        /// <summary>
        /// String to label the units of the chart on the Y-Axis
        /// </summary>
        public readonly string Units;

        [OutputConstructor]
        private DashboardSectionRowChart(
            string? chartAttribute,

            Outputs.DashboardSectionRowChartChartSetting chartSetting,

            string? description,

            string name,

            ImmutableArray<Outputs.DashboardSectionRowChartSource> sources,

            string summarization,

            string units)
        {
            ChartAttribute = chartAttribute;
            ChartSetting = chartSetting;
            Description = description;
            Name = name;
            Sources = sources;
            Summarization = summarization;
            Units = units;
        }
    }
}
