// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Wavefront.Outputs
{

    [OutputType]
    public sealed class GetUsersUserResult
    {
        public readonly string Customer;
        public readonly string Email;
        /// <summary>
        /// When the user last logged in to Wavefront.
        /// </summary>
        public readonly int LastSuccessfulLogin;
        /// <summary>
        /// List of permissions granted to a user.
        /// </summary>
        public readonly ImmutableArray<string> Permissions;
        /// <summary>
        /// List of User Group Ids the user is a member of.
        /// * `customer`- The customer the user is associated with.
        /// </summary>
        public readonly ImmutableArray<string> UserGroupIds;

        [OutputConstructor]
        private GetUsersUserResult(
            string customer,

            string email,

            int lastSuccessfulLogin,

            ImmutableArray<string> permissions,

            ImmutableArray<string> userGroupIds)
        {
            Customer = customer;
            Email = email;
            LastSuccessfulLogin = lastSuccessfulLogin;
            Permissions = permissions;
            UserGroupIds = userGroupIds;
        }
    }
}
