// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package wavefront

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type CloudIntegrationAzureActivityLog struct {
	pulumi.CustomResourceState

	AdditionalTags              pulumi.StringMapOutput   `pulumi:"additionalTags"`
	CategoryFilters             pulumi.StringArrayOutput `pulumi:"categoryFilters"`
	ClientId                    pulumi.StringOutput      `pulumi:"clientId"`
	ClientSecret                pulumi.StringOutput      `pulumi:"clientSecret"`
	ForceSave                   pulumi.BoolPtrOutput     `pulumi:"forceSave"`
	Name                        pulumi.StringOutput      `pulumi:"name"`
	Service                     pulumi.StringOutput      `pulumi:"service"`
	ServiceRefreshRateInMinutes pulumi.IntPtrOutput      `pulumi:"serviceRefreshRateInMinutes"`
	Tenant                      pulumi.StringOutput      `pulumi:"tenant"`
}

// NewCloudIntegrationAzureActivityLog registers a new resource with the given unique name, arguments, and options.
func NewCloudIntegrationAzureActivityLog(ctx *pulumi.Context,
	name string, args *CloudIntegrationAzureActivityLogArgs, opts ...pulumi.ResourceOption) (*CloudIntegrationAzureActivityLog, error) {
	if args == nil || args.ClientId == nil {
		return nil, errors.New("missing required argument 'ClientId'")
	}
	if args == nil || args.ClientSecret == nil {
		return nil, errors.New("missing required argument 'ClientSecret'")
	}
	if args == nil || args.Service == nil {
		return nil, errors.New("missing required argument 'Service'")
	}
	if args == nil || args.Tenant == nil {
		return nil, errors.New("missing required argument 'Tenant'")
	}
	if args == nil {
		args = &CloudIntegrationAzureActivityLogArgs{}
	}
	var resource CloudIntegrationAzureActivityLog
	err := ctx.RegisterResource("wavefront:index/cloudIntegrationAzureActivityLog:CloudIntegrationAzureActivityLog", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCloudIntegrationAzureActivityLog gets an existing CloudIntegrationAzureActivityLog resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCloudIntegrationAzureActivityLog(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CloudIntegrationAzureActivityLogState, opts ...pulumi.ResourceOption) (*CloudIntegrationAzureActivityLog, error) {
	var resource CloudIntegrationAzureActivityLog
	err := ctx.ReadResource("wavefront:index/cloudIntegrationAzureActivityLog:CloudIntegrationAzureActivityLog", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CloudIntegrationAzureActivityLog resources.
type cloudIntegrationAzureActivityLogState struct {
	AdditionalTags              map[string]string `pulumi:"additionalTags"`
	CategoryFilters             []string          `pulumi:"categoryFilters"`
	ClientId                    *string           `pulumi:"clientId"`
	ClientSecret                *string           `pulumi:"clientSecret"`
	ForceSave                   *bool             `pulumi:"forceSave"`
	Name                        *string           `pulumi:"name"`
	Service                     *string           `pulumi:"service"`
	ServiceRefreshRateInMinutes *int              `pulumi:"serviceRefreshRateInMinutes"`
	Tenant                      *string           `pulumi:"tenant"`
}

type CloudIntegrationAzureActivityLogState struct {
	AdditionalTags              pulumi.StringMapInput
	CategoryFilters             pulumi.StringArrayInput
	ClientId                    pulumi.StringPtrInput
	ClientSecret                pulumi.StringPtrInput
	ForceSave                   pulumi.BoolPtrInput
	Name                        pulumi.StringPtrInput
	Service                     pulumi.StringPtrInput
	ServiceRefreshRateInMinutes pulumi.IntPtrInput
	Tenant                      pulumi.StringPtrInput
}

func (CloudIntegrationAzureActivityLogState) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudIntegrationAzureActivityLogState)(nil)).Elem()
}

type cloudIntegrationAzureActivityLogArgs struct {
	AdditionalTags              map[string]string `pulumi:"additionalTags"`
	CategoryFilters             []string          `pulumi:"categoryFilters"`
	ClientId                    string            `pulumi:"clientId"`
	ClientSecret                string            `pulumi:"clientSecret"`
	ForceSave                   *bool             `pulumi:"forceSave"`
	Name                        *string           `pulumi:"name"`
	Service                     string            `pulumi:"service"`
	ServiceRefreshRateInMinutes *int              `pulumi:"serviceRefreshRateInMinutes"`
	Tenant                      string            `pulumi:"tenant"`
}

// The set of arguments for constructing a CloudIntegrationAzureActivityLog resource.
type CloudIntegrationAzureActivityLogArgs struct {
	AdditionalTags              pulumi.StringMapInput
	CategoryFilters             pulumi.StringArrayInput
	ClientId                    pulumi.StringInput
	ClientSecret                pulumi.StringInput
	ForceSave                   pulumi.BoolPtrInput
	Name                        pulumi.StringPtrInput
	Service                     pulumi.StringInput
	ServiceRefreshRateInMinutes pulumi.IntPtrInput
	Tenant                      pulumi.StringInput
}

func (CloudIntegrationAzureActivityLogArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudIntegrationAzureActivityLogArgs)(nil)).Elem()
}
