// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package wavefront

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func GetDefaultUserGroup(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetDefaultUserGroupResult, error) {
	var rv GetDefaultUserGroupResult
	err := ctx.Invoke("wavefront:index/getDefaultUserGroup:getDefaultUserGroup", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getDefaultUserGroup.
type GetDefaultUserGroupResult struct {
	GroupId string `pulumi:"groupId"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
}
