// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package wavefront

import (
	"reflect"

	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type Role struct {
	pulumi.CustomResourceState

	Assignees   pulumi.StringArrayOutput `pulumi:"assignees"`
	Description pulumi.StringPtrOutput   `pulumi:"description"`
	Name        pulumi.StringOutput      `pulumi:"name"`
	Permissions pulumi.StringArrayOutput `pulumi:"permissions"`
}

// NewRole registers a new resource with the given unique name, arguments, and options.
func NewRole(ctx *pulumi.Context,
	name string, args *RoleArgs, opts ...pulumi.ResourceOption) (*Role, error) {
	if args == nil {
		args = &RoleArgs{}
	}
	var resource Role
	err := ctx.RegisterResource("wavefront:index/role:Role", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRole gets an existing Role resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRole(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RoleState, opts ...pulumi.ResourceOption) (*Role, error) {
	var resource Role
	err := ctx.ReadResource("wavefront:index/role:Role", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Role resources.
type roleState struct {
	Assignees   []string `pulumi:"assignees"`
	Description *string  `pulumi:"description"`
	Name        *string  `pulumi:"name"`
	Permissions []string `pulumi:"permissions"`
}

type RoleState struct {
	Assignees   pulumi.StringArrayInput
	Description pulumi.StringPtrInput
	Name        pulumi.StringPtrInput
	Permissions pulumi.StringArrayInput
}

func (RoleState) ElementType() reflect.Type {
	return reflect.TypeOf((*roleState)(nil)).Elem()
}

type roleArgs struct {
	Assignees   []string `pulumi:"assignees"`
	Description *string  `pulumi:"description"`
	Name        *string  `pulumi:"name"`
	Permissions []string `pulumi:"permissions"`
}

// The set of arguments for constructing a Role resource.
type RoleArgs struct {
	Assignees   pulumi.StringArrayInput
	Description pulumi.StringPtrInput
	Name        pulumi.StringPtrInput
	Permissions pulumi.StringArrayInput
}

func (RoleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*roleArgs)(nil)).Elem()
}
