# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'address',
    'http_proxy',
    'token',
]

__config__ = pulumi.Config('wavefront')

address = __config__.get('address')

http_proxy = __config__.get('httpProxy')

token = __config__.get('token')

