// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.wavefront.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetAlertsPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetAlertsPlainArgs Empty = new GetAlertsPlainArgs();

    /**
     * Limit is the maximum number of results to be returned. Defaults to 100.
     * 
     */
    @Import(name="limit")
    private @Nullable Integer limit;

    /**
     * @return Limit is the maximum number of results to be returned. Defaults to 100.
     * 
     */
    public Optional<Integer> limit() {
        return Optional.ofNullable(this.limit);
    }

    /**
     * Offset is the offset from the first result to be returned. Defaults to 0.
     * 
     */
    @Import(name="offset")
    private @Nullable Integer offset;

    /**
     * @return Offset is the offset from the first result to be returned. Defaults to 0.
     * 
     */
    public Optional<Integer> offset() {
        return Optional.ofNullable(this.offset);
    }

    private GetAlertsPlainArgs() {}

    private GetAlertsPlainArgs(GetAlertsPlainArgs $) {
        this.limit = $.limit;
        this.offset = $.offset;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAlertsPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAlertsPlainArgs $;

        public Builder() {
            $ = new GetAlertsPlainArgs();
        }

        public Builder(GetAlertsPlainArgs defaults) {
            $ = new GetAlertsPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param limit Limit is the maximum number of results to be returned. Defaults to 100.
         * 
         * @return builder
         * 
         */
        public Builder limit(@Nullable Integer limit) {
            $.limit = limit;
            return this;
        }

        /**
         * @param offset Offset is the offset from the first result to be returned. Defaults to 0.
         * 
         * @return builder
         * 
         */
        public Builder offset(@Nullable Integer offset) {
            $.offset = offset;
            return this;
        }

        public GetAlertsPlainArgs build() {
            return $;
        }
    }

}
