// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.wavefront.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class GetRolePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetRolePlainArgs Empty = new GetRolePlainArgs();

    /**
     * The ID associated with the role data to be fetched.
     * 
     */
    @Import(name="id", required=true)
    private String id;

    /**
     * @return The ID associated with the role data to be fetched.
     * 
     */
    public String id() {
        return this.id;
    }

    private GetRolePlainArgs() {}

    private GetRolePlainArgs(GetRolePlainArgs $) {
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetRolePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetRolePlainArgs $;

        public Builder() {
            $ = new GetRolePlainArgs();
        }

        public Builder(GetRolePlainArgs defaults) {
            $ = new GetRolePlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id The ID associated with the role data to be fetched.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            $.id = id;
            return this;
        }

        public GetRolePlainArgs build() {
            $.id = Objects.requireNonNull($.id, "expected parameter 'id' to be non-null");
            return $;
        }
    }

}
