// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.wavefront.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class IngestionPolicyState extends com.pulumi.resources.ResourceArgs {

    public static final IngestionPolicyState Empty = new IngestionPolicyState();

    /**
     * The description of the ingestion policy.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return The description of the ingestion policy.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * The name of the ingestion policy.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the ingestion policy.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    private IngestionPolicyState() {}

    private IngestionPolicyState(IngestionPolicyState $) {
        this.description = $.description;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(IngestionPolicyState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private IngestionPolicyState $;

        public Builder() {
            $ = new IngestionPolicyState();
        }

        public Builder(IngestionPolicyState defaults) {
            $ = new IngestionPolicyState(Objects.requireNonNull(defaults));
        }

        /**
         * @param description The description of the ingestion policy.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description The description of the ingestion policy.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param name The name of the ingestion policy.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the ingestion policy.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public IngestionPolicyState build() {
            return $;
        }
    }

}
