// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Wavefront.Inputs
{

    public sealed class AlertAlertTriageDashboardParametersArgs : global::Pulumi.ResourceArgs
    {
        [Input("constants")]
        private InputMap<object>? _constants;
        public InputMap<object> Constants
        {
            get => _constants ?? (_constants = new InputMap<object>());
            set => _constants = value;
        }

        public AlertAlertTriageDashboardParametersArgs()
        {
        }
        public static new AlertAlertTriageDashboardParametersArgs Empty => new AlertAlertTriageDashboardParametersArgs();
    }
}
