// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Wavefront.Inputs
{

    public sealed class DashboardSectionGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of this section.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("rows", required: true)]
        private InputList<Inputs.DashboardSectionRowGetArgs>? _rows;

        /// <summary>
        /// See dashboard section rows.
        /// </summary>
        public InputList<Inputs.DashboardSectionRowGetArgs> Rows
        {
            get => _rows ?? (_rows = new InputList<Inputs.DashboardSectionRowGetArgs>());
            set => _rows = value;
        }

        public DashboardSectionGetArgs()
        {
        }
        public static new DashboardSectionGetArgs Empty => new DashboardSectionGetArgs();
    }
}
