// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class CloudIntegrationNewRelic extends pulumi.CustomResource {
    /**
     * Get an existing CloudIntegrationNewRelic resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CloudIntegrationNewRelicState, opts?: pulumi.CustomResourceOptions): CloudIntegrationNewRelic {
        return new CloudIntegrationNewRelic(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'wavefront:index/cloudIntegrationNewRelic:CloudIntegrationNewRelic';

    /**
     * Returns true if the given object is an instance of CloudIntegrationNewRelic.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CloudIntegrationNewRelic {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CloudIntegrationNewRelic.__pulumiType;
    }

    public readonly additionalTags!: pulumi.Output<{[key: string]: string} | undefined>;
    public readonly apiKey!: pulumi.Output<string>;
    public readonly appFilterRegex!: pulumi.Output<string | undefined>;
    public readonly forceSave!: pulumi.Output<boolean | undefined>;
    public readonly hostFilterRegex!: pulumi.Output<string | undefined>;
    public readonly metricFilters!: pulumi.Output<outputs.CloudIntegrationNewRelicMetricFilter[] | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly service!: pulumi.Output<string>;
    public readonly serviceRefreshRateInMinutes!: pulumi.Output<number | undefined>;

    /**
     * Create a CloudIntegrationNewRelic resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CloudIntegrationNewRelicArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CloudIntegrationNewRelicArgs | CloudIntegrationNewRelicState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as CloudIntegrationNewRelicState | undefined;
            inputs["additionalTags"] = state ? state.additionalTags : undefined;
            inputs["apiKey"] = state ? state.apiKey : undefined;
            inputs["appFilterRegex"] = state ? state.appFilterRegex : undefined;
            inputs["forceSave"] = state ? state.forceSave : undefined;
            inputs["hostFilterRegex"] = state ? state.hostFilterRegex : undefined;
            inputs["metricFilters"] = state ? state.metricFilters : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["service"] = state ? state.service : undefined;
            inputs["serviceRefreshRateInMinutes"] = state ? state.serviceRefreshRateInMinutes : undefined;
        } else {
            const args = argsOrState as CloudIntegrationNewRelicArgs | undefined;
            if (!args || args.apiKey === undefined) {
                throw new Error("Missing required property 'apiKey'");
            }
            if (!args || args.service === undefined) {
                throw new Error("Missing required property 'service'");
            }
            inputs["additionalTags"] = args ? args.additionalTags : undefined;
            inputs["apiKey"] = args ? args.apiKey : undefined;
            inputs["appFilterRegex"] = args ? args.appFilterRegex : undefined;
            inputs["forceSave"] = args ? args.forceSave : undefined;
            inputs["hostFilterRegex"] = args ? args.hostFilterRegex : undefined;
            inputs["metricFilters"] = args ? args.metricFilters : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["service"] = args ? args.service : undefined;
            inputs["serviceRefreshRateInMinutes"] = args ? args.serviceRefreshRateInMinutes : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(CloudIntegrationNewRelic.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CloudIntegrationNewRelic resources.
 */
export interface CloudIntegrationNewRelicState {
    readonly additionalTags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    readonly apiKey?: pulumi.Input<string>;
    readonly appFilterRegex?: pulumi.Input<string>;
    readonly forceSave?: pulumi.Input<boolean>;
    readonly hostFilterRegex?: pulumi.Input<string>;
    readonly metricFilters?: pulumi.Input<pulumi.Input<inputs.CloudIntegrationNewRelicMetricFilter>[]>;
    readonly name?: pulumi.Input<string>;
    readonly service?: pulumi.Input<string>;
    readonly serviceRefreshRateInMinutes?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a CloudIntegrationNewRelic resource.
 */
export interface CloudIntegrationNewRelicArgs {
    readonly additionalTags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    readonly apiKey: pulumi.Input<string>;
    readonly appFilterRegex?: pulumi.Input<string>;
    readonly forceSave?: pulumi.Input<boolean>;
    readonly hostFilterRegex?: pulumi.Input<string>;
    readonly metricFilters?: pulumi.Input<pulumi.Input<inputs.CloudIntegrationNewRelicMetricFilter>[]>;
    readonly name?: pulumi.Input<string>;
    readonly service: pulumi.Input<string>;
    readonly serviceRefreshRateInMinutes?: pulumi.Input<number>;
}
