// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Provides an External ID for use in Amazon Web Services IAM Roles. This allows External IDs to be created and deleted.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as wavefront from "@pulumi/wavefront";
 *
 * const externalId = new wavefront.CloudIntegrationAwsExternalId("externalId", {});
 * ```
 *
 * ## Import
 *
 * External IDs can be imported by using the `id`, e.g.
 *
 * ```sh
 *  $ pulumi import wavefront:index/cloudIntegrationAwsExternalId:CloudIntegrationAwsExternalId external_id uGJdkH3k
 * ```
 */
export class CloudIntegrationAwsExternalId extends pulumi.CustomResource {
    /**
     * Get an existing CloudIntegrationAwsExternalId resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CloudIntegrationAwsExternalIdState, opts?: pulumi.CustomResourceOptions): CloudIntegrationAwsExternalId {
        return new CloudIntegrationAwsExternalId(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'wavefront:index/cloudIntegrationAwsExternalId:CloudIntegrationAwsExternalId';

    /**
     * Returns true if the given object is an instance of CloudIntegrationAwsExternalId.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CloudIntegrationAwsExternalId {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CloudIntegrationAwsExternalId.__pulumiType;
    }


    /**
     * Create a CloudIntegrationAwsExternalId resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: CloudIntegrationAwsExternalIdArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CloudIntegrationAwsExternalIdArgs | CloudIntegrationAwsExternalIdState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CloudIntegrationAwsExternalIdState | undefined;
        } else {
            const args = argsOrState as CloudIntegrationAwsExternalIdArgs | undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CloudIntegrationAwsExternalId.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CloudIntegrationAwsExternalId resources.
 */
export interface CloudIntegrationAwsExternalIdState {
}

/**
 * The set of arguments for constructing a CloudIntegrationAwsExternalId resource.
 */
export interface CloudIntegrationAwsExternalIdArgs {
}
