// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Use this data source to get information about all Wavefront alerts.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as wavefront from "@pulumi/wavefront";
 *
 * // Get the information about all alerts.
 * const example = wavefront.getAlerts({
 *     limit: 10,
 *     offset: 0,
 * });
 * ```
 */
export function getAlerts(args?: GetAlertsArgs, opts?: pulumi.InvokeOptions): Promise<GetAlertsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("wavefront:index/getAlerts:getAlerts", {
        "limit": args.limit,
        "offset": args.offset,
    }, opts);
}

/**
 * A collection of arguments for invoking getAlerts.
 */
export interface GetAlertsArgs {
    /**
     * Limit is the maximum number of results to be returned. Defaults to 100.
     */
    limit?: number;
    /**
     * Offset is the offset from the first result to be returned. Defaults to 0.
     */
    offset?: number;
}

/**
 * A collection of values returned by getAlerts.
 */
export interface GetAlertsResult {
    /**
     * List of all alerts in Wavefront. For each alert you will see a list of attributes.
     */
    readonly alerts: outputs.GetAlertsAlert[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly limit?: number;
    readonly offset?: number;
}
/**
 * Use this data source to get information about all Wavefront alerts.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as wavefront from "@pulumi/wavefront";
 *
 * // Get the information about all alerts.
 * const example = wavefront.getAlerts({
 *     limit: 10,
 *     offset: 0,
 * });
 * ```
 */
export function getAlertsOutput(args?: GetAlertsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAlertsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("wavefront:index/getAlerts:getAlerts", {
        "limit": args.limit,
        "offset": args.offset,
    }, opts);
}

/**
 * A collection of arguments for invoking getAlerts.
 */
export interface GetAlertsOutputArgs {
    /**
     * Limit is the maximum number of results to be returned. Defaults to 100.
     */
    limit?: pulumi.Input<number>;
    /**
     * Offset is the offset from the first result to be returned. Defaults to 0.
     */
    offset?: pulumi.Input<number>;
}
