// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getMetricsPolicy(opts?: pulumi.InvokeOptions): Promise<GetMetricsPolicyResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("wavefront:index/getMetricsPolicy:getMetricsPolicy", {
    }, opts);
}

/**
 * A collection of values returned by getMetricsPolicy.
 */
export interface GetMetricsPolicyResult {
    readonly customer: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly policyRules: outputs.GetMetricsPolicyPolicyRule[];
    readonly updatedEpochMillis: number;
    readonly updaterId: string;
}
export function getMetricsPolicyOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetMetricsPolicyResult> {
    return pulumi.output(getMetricsPolicy(opts))
}
